package com.manorbuttys.api.menu.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Setter;

import java.math.BigDecimal;

@DynamoDBTable(tableName = "Menu")
@Setter
public class Item {

    private String id;
    private String category;
    private String name;
    private int count;
    private BigDecimal price;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    @DynamoDBAttribute
    public String getCategory(){
        return category;
    }

    @DynamoDBAttribute
    public String getName() {
        return name;
    }
    @DynamoDBAttribute
    public int getCount() {
        return count;
    }
    @DynamoDBAttribute
    public BigDecimal getPrice() {
        return price;
    }
}
